### PR TITLE
simple docker deployment

### PR DESCRIPTION
**Pull request by DocBrown101**

### CODE REVIEW

**Comment by martin-ueding** [comment]
What is the advantage of running it in Docker over a virtual environment or just with the system wide installation of Python?

**Comment by DocBrown101** [comment]
There are many advantages with docker. If only because you have the choice to use it or not.
Here is a small excerpt of a short google research:

Portability
Once you have tested your containerized application you can deploy it to any other system where Docker is running and you can be sure that your application will perform exactly as it did when you tested it.

Performance
Although virtual machines are an alternative to containers, the fact that containers do not contain an operating system (whereas virtual machines do) means that containers have much smaller footprints than virtual machines, are faster to create, and quicker to start.

Agility
The portability and performance benefits offered by containers can help you make your development process more agile and responsive. Enhancing your continuous integration and continuous delivery processes to take advantage of containers and technology such as Enterprise Developer Build Tools for Windows makes it easier for you to deliver the right software at the right time. Enterprise Developer Build Tools for Windows is a component of Enterprise Developer which provides all of the functionality of Enterprise Developer to enable you to compile, build, and test COBOL code but without the overhead of an IDE.

Isolation
A Docker container that contains one of your applications also includes the relevant versions of any supporting software that your application requires. If other Docker containers contain applications that require different versions of the same supporting software, that isn't a problem because the different Docker containers are totally independent of one other.

This also means that as you move through the various stages of your development lifecycle, you can have total confidence that an image you create during development will perform exactly the same as it moves through testing and potentially to your users.

Scalability
You can quickly create new containers if demand for your applications requires them. When using multiple containers you can take advantage of a range of container management options. See the Docker documentation for more information on these options.

**Comment by martin-ueding** [comment]
Sure, Docker can be great for complicated things. I also use it at work. But what problem does it solve here? The deployment isn't particularly complex. Why are you using it with Docker?

**Comment by DocBrown101** [comment]
My whole self-hosted environment is built on docker. I use docker for monitoring alone.

**Pull request merged**
